export const idioms: string[] = [
    "A Bit Much",
    "A Bite at The Cherry",
    "A Busy Bee",
    "A Cat Has Nine Lives",
    "A Cat Nap",
    "A Cat in Gloves Catches No Mice",
    "A Cold Day In July",
    "A Cold Fish",
    "A Cut Above",
    "A Cut Below",
    "A Day Late And A Dollar Short",
    "A Dog in The Manger",
    "A Few Sandwiches Short Of A Picnic",
    "A Good Deal",
    "A Guinea Pig",
    "A Hair's Breadth",
    "A Home Bird",
    "A Hundred And Ten Percent",
    "A Lame Duck",
    "A Leg Up",
    "A Lemon",
    "A Life Of Its Own",
    "A Little Bird Told Me",
    "A Little from Column A, a Little from Column B",
    "A Lone Wolf",
    "A Lot on One's Plate",
    "A Million and One",
    "A Notch Above",
    "A Penny Saved is A Penny Earned",
    "A Penny for Your Thoughts",
    "A Picture Is Worth a Thousand Words",
    "A Plum Job",
    "A Rare Bird",
    "A Scaredy-Cat",
    "A Second Bite At The Cherry",
    "A Sight for Sore Eyes",
    "A Sitting Duck",
    "A Snowball's Chance in Hell",
    "A Stitch in Time Saves Nine",
    "A Stone's Throw",
    "A Storm in a Teacup",
    "A Tall Order",
    "About Time",
    "About To",
    "Above And Beyond",
    "Above Board",
    "Ace In The Hole",
    "Achilles' Heel",
    "Acid Test",
    "Add Fuel To The Fire",
    "Against The Clock",
    "Ahead Of The Curve",
    "Air One's Dirty Laundry",
    "All Bark And No Bite",
    "All Ears",
    "All In The Same Boat",
    "All Thumbs",
    "An Arm And A Leg",
    "An Axe To Grind",
    "Apple Of My Eye",
    "As Easy As Pie",
    "As Fit As A Fiddle",
    "As Good As Gold",
    "As Right As Rain",
    "At Loggerheads",
    "At The Drop Of A Hat",
    "Back To The Drawing Board",
    "Backseat Driver",
    "Barking Up The Wrong Tree",
    "Beating Around The Bush",
    "Bite Off More Than You Can Chew",
    "Bite The Bullet",
    "Bite The Dust",
    "Black Sheep",
    "Blow Off Steam",
    "Break A Leg",
    "Break The Ice",
    "Bring Home The Bacon",
    "Burn The Midnight Oil",
    "Burning The Candle At Both Ends",
    "Bury The Hatchet",
    "By The Skin Of Your Teeth",
    "Call It A Day",
    "Caught Between A Rock And A Hard Place",
    "Caught Red-Handed",
    "Change Of Heart",
    "Clam Up",
    "Cold Feet",
    "Come Rain Or Shine",
    "Cost An Arm And A Leg",
    "Couch Potato",
    "Cry Over Spilled Milk",
    "Cut Corners",
    "Cut The Mustard",
    "Devil's Advocate",
    "Don't Count Your Chickens Before They Hatch",
    "Don't Cry Over Spilled Milk",
    "Don't Give Up Your Day Job",
    "Don't Put All Your Eggs In One Basket",
    "Down To The Wire",
    "Draw The Line",
    "Drop A Dime",
    "Easier Said Than Done",
    "Every Cloud Has A Silver Lining",
    "Face The Music",
    "Feather In One's Cap",
    "Feel Under The Weather",
    "Fifth Wheel",
    "Fish Out Of Water",
    "Fly Off The Handle",
    "For A Song",
    "Get A Taste Of Your Own Medicine",
    "Get Cold Feet",
    "Get Out Of Hand",
    "Get The Ball Rolling",
    "Give Someone The Cold Shoulder",
    "Go The Extra Mile",
    "Go With The Flow",
    "Grasp At Straws",
    "Green With Envy",
    "Hang In There",
    "Have A Blast",
    "Have A Chip On One's Shoulder",
    "Have A Sweet Tooth",
    "Hit The Books",
    "Hit The Hay",
    "Hit The Nail On The Head",
    "Hit The Sack",
    "In Hot Water",
    "In The Blink Of An Eye",
    "In The Same Boat",
    "It's Not Rocket Science",
    "Jump On The Bandwagon",
    "Keep An Eye On",
    "Keep Your Chin Up",
    "Kick The Bucket",
    "Kill Two Birds With One Stone",
    "Know The Ropes",
    "Last Straw",
    "Let Sleeping Dogs Lie",
    "Let The Cat Out Of The Bag",
    "Like Two Peas In A Pod",
    "Make A Long Story Short",
    "Miss The Boat",
    "No Pain, No Gain",
    "Off The Hook",
    "On Cloud Nine",
    "On The Ball",
    "On The Fence",
    "Once In A Blue Moon",
    "Out Of The Blue",
    "Out Of The Frying Pan And Into The Fire",
    "Over The Moon",
    "Piece Of Cake",
    "Pull Someone's Leg",
    "Put All Your Eggs In One Basket",
    "Put Your Money Where Your Mouth Is",
    "Rain On Someone's Parade",
    "Raining Cats And Dogs",
    "Read Between The Lines",
    "Renting a Pedal Boat",
    "Rock The Boat",
    "Rome Wasn't Built In A Day",
    "Run Out Of Steam",
    "Saved By The Bell",
    "See Eye To Eye",
    "Shoot The Breeze",
    "Sit On The Fence",
    "Sleep On It",
    "Spill The Beans",
    "Steal Someone's Thunder",
    "Take It With A Grain Of Salt",
    "Take The Bull By The Horns",
    "The Ball Is In Your Court",
    "The Best Of Both Worlds",
    "The Early Bird Catches The Worm",
    "The Elephant In The Room",
    "The Last Straw",
    "The Whole Nine Yards",
    "Throw In The Towel",
    "Tie The Knot",
    "Time Flies When You're Having Fun",
    "To Add Insult To Injury",
    "To Be On The Safe Side",
    "To Burn Bridges",
    "To Cut To The Chase",
    "To Feel Blue",
    "To Hit The Jackpot",
    "To Make A Mountain Out Of A Molehill",
    "To Pull Strings",
    "To Put It In A Nutshell",
    "To Throw Caution To The Wind",
    "Turn A Blind Eye",
    "Under The Weather",
    "Up In The Air",
    "Walking On Air",
    "When Pigs Fly",
    "You Can't Judge A Book By Its Cover",
    "You Scratch My Back And I'll Scratch Yours",
    "Your Guess Is As Good As Mine"
];
